version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: compliance_copilot
      POSTGRES_USER: compliance
      POSTGRES_PASSWORD: compliance
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "compliance"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
